name = "day9"
version = "0.1.0"
defaultTargets = ["day9"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Day9"

[[lean_exe]]
name = "day9"
root = "Main"
