name = "day15"
version = "0.1.0"
defaultTargets = ["day15"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Day15"

[[lean_exe]]
name = "day15"
root = "Main"
