name = "day4"
version = "0.1.0"
defaultTargets = ["day4"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Day4"

[[lean_exe]]
name = "day4"
root = "Main"
