name = "day6"
version = "0.1.0"
defaultTargets = ["day6"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Day6"

[[lean_exe]]
name = "day6"
root = "Main"
