name = "day7"
version = "0.1.0"
defaultTargets = ["day7"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Day7"

[[lean_exe]]
name = "day7"
root = "Main"
